# Generated by Django 3.2.4 on 2021-11-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_name', models.CharField(max_length=500)),
                ('cus_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('cus_address', models.CharField(max_length=500)),
                ('cus_mobile', models.CharField(max_length=500)),
                ('cus_email', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=500)),
                ('prod_cost_price', models.IntegerField()),
                ('prod_sell_price', models.IntegerField()),
                ('prod_qty', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('mob_no', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=500)),
                ('user_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=500)),
                ('user_mob', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('cus_id', models.CharField(max_length=500)),
                ('qty', models.IntegerField()),
                ('sales_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('profit', models.IntegerField(blank=True, null=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.user')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.user')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('raw_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('raw_name', models.CharField(max_length=500)),
                ('sup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.supplier')),
            ],
            options={
                'db_table': 'raw_material',
            },
        ),
        migrations.CreateModel(
            name='RaisedIssue',
            fields=[
                ('reason', models.CharField(max_length=500)),
                ('sales_id', models.CharField(max_length=500)),
                ('qty', models.IntegerField()),
                ('raised_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.customer')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.product')),
            ],
            options={
                'db_table': 'raised_issue',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('login_username', models.CharField(max_length=500)),
                ('user_password', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.user')),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='RolesRoleDesc',
            fields=[
                ('role_desc', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.roles')),
            ],
            options={
                'db_table': 'roles_role_desc',
                'unique_together': {('role_desc', 'role')},
            },
        ),
        migrations.CreateModel(
            name='HasProRaw',
            fields=[
                ('prod', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app1.product')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.rawmaterial')),
            ],
            options={
                'db_table': 'has_pro_raw',
                'unique_together': {('prod', 'raw')},
            },
        ),
    ]
